export const API = 
[
      {
        id: 1,
        email: "user1@example.com",
        body: "Tao ghét Spring Boot",
        liked:false,
        like:680,
        comment:240,
        share: 110,
      },
      {
        id: 2,
        email: "user2@example.com",
        body: "Ai có tips học React nhanh thì chia sẻ với mình với",
        liked:false,
        like: 110,
        comment: 670,
        share: 20,
      },
      {
        id: 3,
        email: "user3@example.com",
        body: "Mới deploy xong dự án đầu tiên, cảm giác phê cực",
        liked:false,
        like: 240,
        comment: 250,
        share: 0,
      },
      {
        id: 4,
        email: "user4@example.com",
        body: "Chơi game hoài mà bug chưa fix được",
        liked:false,
        like: 10,
        comment: 240,
        share: 0,
      },
      {
        id: 5,
        email: "user5@example.com",
        body: "Đi phỏng vấn lần đầu, run muốn xỉu",
        liked:false,
        like: 0,
        comment: 0,
        share: 0,
      },
      {
        id: 6,
        email: "user6@example.com",
        body: "Mới học xong useReducer, giờ áp dụng thử nè",
        liked:false,
        like: 12,
        comment: 120,
        share: 0,
      },
      {
        id: 7,
        email: "user7@example.com",
        body: "Backend xong rồi, frontend tới lượt ai làm đây?",
        liked:false,
        like: 100,
        comment: 20,
        share: 0,
      },
      {
        id: 8,
        email: "user8@example.com",
        body: "Ăn no quá, buồn ngủ nhưng vẫn phải ngồi học code",
        liked:false,
        like: 0,
        comment: 0,
        share: 0,
      },
      {
        id: 9,
        email: "user9@example.com",
        body: "Code ban ngày bug, code ban đêm cũng bug",
        liked:false,
        like: 10,
        comment: 30,
        share: 0,
      },
      {
        id: 10,
        email: "user10@example.com",
        body: "Thích nhất cảm giác khi app chạy đúng ngay lần đầu",
        liked:false,
        like: 60,
        comment: 20,
        share: 30,
      }
]
